# Makefile for Java Bozo Game

.PHONY: all run clean

# Compile all Java files
all:
	javac Bozo.java Dado.java EntradaTeclado.java Placar.java RolaDados.java

# Run the game
run:
	java Bozo

# Clean compiled class files
clean:
	rm -f *.class